// Chappy5 hall shell v0.3
// Dense top-view pixel-art foundation: portrait hall, bottom entrance, floor and walls only.
(() => {
'use strict';
const canvas=document.getElementById('hall'),ctx=canvas.getContext('2d');
const WORLD={w:820,h:1280},view={x:0,y:0,zoom:1},pointers=new Map();
let dragStart=null,pinchStart=null,lastTap=0,dpr=1;
const C={void:'#111516',wallDark:'#343738',wall:'#555655',wallLight:'#77756f',cap:'#949087',trim:'#3e403e',floor:'#8f7358',tile1:'#a88968',tile2:'#9c7d5e',tile3:'#927355',line:'#755c46',speck:'#6d5746',shine:'#b99a76',frame:'#3c4547',glass:'#58747a',glassHi:'#81999a',mat:'#55483e',metal:'#8b8b84'};
const size=()=>{const r=canvas.getBoundingClientRect();return{width:r.width,height:r.height,left:r.left,top:r.top}};
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}
function resize(){const r=size();dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(r.width*dpr));canvas.height=Math.max(1,Math.round(r.height*dpr));fitView();draw()}
function fitView(){const r=size(),z=Math.min(r.width/WORLD.w,r.height/WORLD.h)*.96;view.zoom=z;view.x=Math.round((r.width-WORLD.w*z)/2);view.y=Math.round((r.height-WORLD.h*z)/2)}
function pixelTile(x,y,s,row,col){const base=(row+col)%3===0?C.tile1:(row+col)%3===1?C.tile2:C.tile3;rect(x,y,s,s,base);rect(x,y,s,2,C.line);rect(x,y,2,s,C.line);if((row*7+col*11)%5===0){rect(x+7,y+8,3,2,C.speck);rect(x+21,y+20,2,3,C.speck)}if((row*3+col*5)%7===0)rect(x+13,y+5,7,2,C.shine)}
function floor(x,y,w,h){rect(x,y,w,h,C.floor);const s=32;for(let yy=y,r=0;yy<y+h;yy+=s,r++)for(let xx=x,c=0;xx<x+w;xx+=s,c++)pixelTile(xx,yy,Math.min(s,x+w-xx),r,c);ctx.globalAlpha=.12;[[150,280,230,10],[420,430,190,8],[230,690,260,10],[400,900,210,8],[250,1080,280,10]].forEach(p=>rect(...p,C.speck));ctx.globalAlpha=1}
function wallBand(x,y,w,h,vertical=false){rect(x,y,w,h,C.wallDark);if(vertical){rect(x+8,y,w-16,h,C.wall);rect(x+13,y,w-26,h,C.wallLight);for(let yy=y+20;yy<y+h;yy+=64){rect(x+13,yy,w-26,2,C.cap);rect(x+16,yy+3,w-32,2,C.trim)}}else{rect(x,y+8,w,h-16,C.wall);rect(x,y+13,w,h-26,C.wallLight);for(let xx=x+20;xx<x+w;xx+=64){rect(xx,y+13,2,h-26,C.cap);rect(xx+3,y+16,2,h-32,C.trim)}}}
function walls(){wallBand(45,35,730,40,false);wallBand(45,35,40,1210,true);wallBand(735,35,40,1210,true);wallBand(45,1205,299,40,false);wallBand(476,1205,299,40,false);rect(76,66,668,8,C.trim);rect(76,66,8,1144,C.trim);rect(736,66,8,1144,C.trim);rect(76,1202,268,8,C.trim);rect(476,1202,268,8,C.trim);rect(55,45,10,10,C.cap);rect(755,45,10,10,C.cap);rect(55,1225,10,10,C.cap);rect(755,1225,10,10,C.cap)}
function entrance(){const x=344,y=1202,w=132,h=43;rect(x,y,w,h,C.void);rect(x-5,y-3,w+10,5,C.metal);rect(x,y,9,h,C.frame);rect(x+w-9,y,9,h,C.frame);rect(x+9,y,54,h-4,C.glass);rect(x+69,y,54,h-4,C.glass);rect(x+63,y,6,h-4,C.frame);rect(x+14,y+6,42,3,C.glassHi);rect(x+74,y+6,42,3,C.glassHi);rect(x+18,y+12,3,16,C.glassHi);rect(x+78,y+12,3,16,C.glassHi);rect(x+12,y-30,w-24,24,C.mat);for(let yy=y-27;yy<y-9;yy+=4)for(let xx=x+16;xx<x+w-16;xx+=8)if(((xx+yy)/4)%2<1)rect(xx,yy,4,2,'#6b5b4d')}
function hall(){rect(0,0,WORLD.w,WORLD.h,C.void);floor(76,66,668,1144);walls();entrance()}
function draw(){ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.setTransform(dpr*view.zoom,0,0,dpr*view.zoom,dpr*view.x,dpr*view.y);ctx.imageSmoothingEnabled=false;hall()}
function clampZoom(z){const fit=Math.min(canvas.clientWidth/WORLD.w,canvas.clientHeight/WORLD.h)*.96;return Math.max(fit*.85,Math.min(3,z))}
function beginPinch(){const r=size(),p=[...pointers.values()];if(p.length!==2)return;const mx=(p[0].x+p[1].x)/2-r.left,my=(p[0].y+p[1].y)/2-r.top;pinchStart={d:Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y),zoom:view.zoom,worldX:(mx-view.x)/view.zoom,worldY:(my-view.y)/view.zoom};dragStart=null}
canvas.addEventListener('wheel',e=>{e.preventDefault();const r=size(),sx=e.clientX-r.left,sy=e.clientY-r.top,wx=(sx-view.x)/view.zoom,wy=(sy-view.y)/view.zoom;view.zoom=clampZoom(view.zoom*(e.deltaY<0?1.12:.89));view.x=sx-wx*view.zoom;view.y=sy-wy*view.zoom;draw()},{passive:false});
canvas.addEventListener('pointerdown',e=>{e.preventDefault();canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1){dragStart={px:e.clientX,py:e.clientY,vx:view.x,vy:view.y};pinchStart=null}else if(pointers.size===2)beginPinch()});
canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1&&dragStart){view.x=dragStart.vx+e.clientX-dragStart.px;view.y=dragStart.vy+e.clientY-dragStart.py;draw();return}if(pointers.size===2&&pinchStart){const r=size(),p=[...pointers.values()],d=Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y),mx=(p[0].x+p[1].x)/2-r.left,my=(p[0].y+p[1].y)/2-r.top;view.zoom=clampZoom(pinchStart.zoom*d/Math.max(1,pinchStart.d));view.x=mx-pinchStart.worldX*view.zoom;view.y=my-pinchStart.worldY*view.zoom;draw()}},{passive:false});
function end(e){pointers.delete(e.pointerId);if(pointers.size===1){const p=[...pointers.values()][0];dragStart={px:p.x,py:p.y,vx:view.x,vy:view.y};pinchStart=null}else{dragStart=null;pinchStart=null}}
canvas.addEventListener('pointerup',e=>{end(e);const n=Date.now();if(n-lastTap<300){fitView();draw()}lastTap=n});canvas.addEventListener('pointercancel',end);canvas.addEventListener('dblclick',()=>{fitView();draw()});canvas.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('resize',resize,{passive:true});window.addEventListener('orientationchange',()=>setTimeout(resize,80),{passive:true});resize();
})();