window.ZELVOLT_SYMBOLS={
  "7R":"/Chappy5/src/game/slot-pachiro/machines/zelvolt/symbols/7R.webp?v=128-1",
  "7W":"/Chappy5/src/game/slot-pachiro/machines/zelvolt/symbols/7W.webp?v=128-1",
  "BAR":"/Chappy5/src/game/slot-pachiro/machines/zelvolt/symbols/BAR.webp?v=128-1",
  "CHERRY":"/Chappy5/src/game/slot-pachiro/machines/zelvolt/symbols/CHERRY.webp?v=128-1",
  "GRAPE":"/Chappy5/src/game/slot-pachiro/machines/zelvolt/symbols/GRAPE.webp?v=128-1",
  "BELL":"/Chappy5/src/game/slot-pachiro/machines/zelvolt/symbols/BELL.webp?v=128-1",
  "REPLAY":"/Chappy5/src/game/slot-pachiro/machines/zelvolt/symbols/REPLAY.webp?v=128-1"
};
