import { bindPlacementCursorControls, createPlacementCursor } from './cursor.js';
import { createCustomer, planCustomerTo, advanceCustomer, CUSTOMER_STATES } from './customer.js';
import { layout, validateLayout } from './layout.js';
import { findPath } from './navigation.js';
import { renderCustomerActor, renderLayout, updateCustomerActor } from './renderer.js';

const fmt = new Intl.NumberFormat('ja-JP');
const GAME_TICK_MS = 220;
const OPEN_MINUTE = 10 * 60;
const CLOSE_MINUTE = 21 * 60;
const SAVE_KEY = 'slot-pachiro-main-v1';
const CUSTOMER_TYPES = Object.freeze({regular:Object.freeze({label:'常連',spend:1,dwell:1,weight:58}),quick:Object.freeze({label:'短時間客',spend:.72,dwell:.68,weight:27}),high:Object.freeze({label:'高単価客',spend:1.55,dwell:1.35,weight:15})});
const els={scene:document.getElementById('scene'),frame:document.getElementById('scene-frame'),vp:document.getElementById('vp'),date:document.getElementById('dateLabel'),time:document.getElementById('timeLabel'),popularity:document.getElementById('popularityLabel'),visitors:document.getElementById('visitorLabel'),cash:document.getElementById('cashLabel'),sales:document.getElementById('salesLabel'),occ:document.getElementById('occupancyLabel'),status:document.getElementById('gameStatus'),event:document.getElementById('eventText'),panel:document.getElementById('gamePanel'),panelTitle:document.getElementById('panelTitle'),panelBody:document.getElementById('panelBody')};
if(!els.scene||!els.frame||!els.vp)throw new Error('Slot Pachiro canonical roots are missing');
function loadMeta(){try{const raw=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');if(!raw||typeof raw!=='object')throw new Error('empty');return{day:Math.max(1,Number(raw.day)||1),cash:Math.max(0,Number(raw.cash)||3_000_000),popularity:Math.max(1,Math.min(99,Number(raw.popularity)||13)),research:Math.max(0,Number(raw.research)||0),lifetimeSales:Math.max(0,Number(raw.lifetimeSales)||0),lifetimeVisitors:Math.max(0,Number(raw.lifetimeVisitors)||0)}}catch{return{day:1,cash:3_000_000,popularity:13,research:0,lifetimeSales:0,lifetimeVisitors:0}}}
const meta=loadMeta();let activeLayout=layout,report=validateLayout(activeLayout),day=meta.day,gameMinute=OPEN_MINUTE,cash=meta.cash,popularity=meta.popularity,researchLevel=meta.research,lifetimeSales=meta.lifetimeSales,lifetimeVisitors=meta.lifetimeVisitors,sales=0,dayVisitors=0,speed=1,zoom=1,customerSeq=0,spawnClock=0,buildCursor=null,buildPanel=null,daySettled=false,adBoost=0,serviceBoost=0;const customers=new Map(),islandStats=new Map(activeLayout.islands.map(i=>[i.id,{plays:0,revenue:0}])),segmentStats={regular:0,quick:0,high:0};
function persist(){localStorage.setItem(SAVE_KEY,JSON.stringify({day,cash,popularity,research:researchLevel,lifetimeSales,lifetimeVisitors}))}
function calendarLabel(){const year=Math.floor((day-1)/336)+1,yearDay=(day-1)%336,month=Math.floor(yearDay/28)+1,week=Math.floor((yearDay%28)/7)+1;return`${year}年目 ${month}月 ${week}週`}
function formatTime(minute){const h=Math.floor(minute/60)%24,m=minute%60;return`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`}
function setEvent(text){els.event.textContent=text}function machineMultiplier(){return 1+researchLevel*.08+serviceBoost*.04}
function updateHud(){els.date.textContent=calendarLabel();els.time.textContent=formatTime(gameMinute);els.popularity.textContent=String(popularity+adBoost);els.visitors.textContent=String(dayVisitors);els.cash.textContent=`${fmt.format(Math.round(cash))}G`;els.sales.textContent=`+${fmt.format(Math.round(sales))}G`;const seated=[...customers.values()].filter(c=>c.model.state===CUSTOMER_STATES.SEATED&&c.phase==='play').length;els.occ.textContent=`${Math.min(100,Math.round(seated/36*100))}%`;els.status.textContent=daySettled?'営業終了':speed===0?'一時停止':gameMinute>=CLOSE_MINUTE?'閉店作業':'営業中'}
function applyZoom(nextZoom,anchorX=els.vp.clientWidth/2,anchorY=els.vp.clientHeight/2){nextZoom=Math.max(.72,Math.min(1.55,nextZoom));const old=zoom,worldX=(els.vp.scrollLeft+anchorX)/old,worldY=(els.vp.scrollTop+anchorY)/old;zoom=nextZoom;const w=Number(els.scene.dataset.baseWidth||730),h=Number(els.scene.dataset.baseHeight||720);els.scene.style.transform=`scale(${zoom})`;els.frame.style.width=`${Math.ceil(w*zoom)}px`;els.frame.style.height=`${Math.ceil(h*zoom)}px`;els.vp.scrollLeft=worldX*zoom-anchorX;els.vp.scrollTop=worldY*zoom-anchorY}
function centerCamera(){requestAnimationFrame(()=>{applyZoom(1.08);els.vp.scrollLeft=Math.max(0,(els.frame.scrollWidth-els.vp.clientWidth)/2);els.vp.scrollTop=Math.max(0,els.frame.scrollHeight*.17)})}
function installCameraControls(){let drag=null;els.vp.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,left:els.vp.scrollLeft,top:els.vp.scrollTop};els.vp.setPointerCapture(e.pointerId);els.vp.classList.add('dragging');document.getElementById('cameraHint')?.classList.add('hide')});els.vp.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;els.vp.scrollLeft=drag.left-(e.clientX-drag.x);els.vp.scrollTop=drag.top-(e.clientY-drag.y)});const end=e=>{if(drag&&e.pointerId===drag.id){drag=null;els.vp.classList.remove('dragging')}};els.vp.addEventListener('pointerup',end);els.vp.addEventListener('pointercancel',end);els.vp.addEventListener('wheel',e=>{if(!e.ctrlKey)return;e.preventDefault();applyZoom(zoom*(e.deltaY>0?.92:1.08),e.clientX,e.clientY)},{passive:false});let pinch=null;els.vp.addEventListener('touchstart',e=>{if(e.touches.length===2){const[a,b]=e.touches;pinch={d:Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY),z:zoom}}},{passive:true});els.vp.addEventListener('touchmove',e=>{if(e.touches.length!==2||!pinch)return;e.preventDefault();const[a,b]=e.touches,d=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY);applyZoom(pinch.z*d/pinch.d,(a.clientX+b.clientX)/2,(a.clientY+b.clientY)/2)},{passive:false});els.vp.addEventListener('touchend',e=>{if(e.touches.length<2)pinch=null},{passive:true})}
function machinePorts(){return report.ports.filter(p=>p.role==='machine-seat'&&report.reachable.has(`${p.x},${p.y}`))}function portal(){return report.ports.find(p=>p.portal)}
function chooseCustomerType(){const highBonus=Math.max(0,popularity+adBoost-15)*.5,weights={regular:58,quick:27,high:15+highBonus};let roll=Math.random()*Object.values(weights).reduce((a,b)=>a+b,0);for(const key of Object.keys(weights)){roll-=weights[key];if(roll<=0)return key}return'regular'}
function spawnThreshold(){return Math.max(3,9-Math.floor((popularity+adBoost)/8))}
function spawnCustomer(){if(gameMinute>=CLOSE_MINUTE||daySettled||customers.size>=Math.min(22,10+Math.floor((popularity+adBoost)/5)))return;const entry=portal(),ports=machinePorts();if(!entry||!ports.length)return;const target=ports[Math.floor(Math.random()*ports.length)],type=chooseCustomerType(),profile=CUSTOMER_TYPES[type];let model=createCustomer(`guest-${++customerSeq}`,entry);try{model=planCustomerTo(model,target,report.map)}catch{return}const actor=renderCustomerActor(els.scene,model,type);const baseDwell=10+Math.floor(Math.random()*13);customers.set(model.id,{model,actor,phase:'toMachine',dwell:Math.max(5,Math.round(baseDwell*profile.dwell)),spendClock:0,target,type});dayVisitors++;lifetimeVisitors++;segmentStats[type]++;setEvent(`${profile.label} 来店 → ${target.facilityId}`)}
function beginExit(record){const exit=portal();if(!exit)return;const route=findPath(record.model,exit,report.map);if(!route){record.phase='leave';return}record.model=Object.freeze({...record.model,state:CUSTOMER_STATES.WALKING,route:Object.freeze(route.map(p=>Object.freeze({...p}))),routeIndex:0,target:Object.freeze({x:exit.x,y:exit.y})});record.phase='toExit'}
function advanceCustomers(){for(const[id,record]of customers){if(record.phase==='toMachine'||record.phase==='toExit'){record.model=advanceCustomer(record.model);updateCustomerActor(record.actor,record.model);if(record.model.state===CUSTOMER_STATES.SEATED){if(record.phase==='toMachine'){record.phase='play';const stat=islandStats.get(record.target.facilityId);if(stat)stat.plays++;setEvent(`${CUSTOMER_TYPES[record.type].label} 遊技開始`)}else record.phase='leave'}}else if(record.phase==='play'){record.dwell--;record.spendClock++;if(record.spendClock%3===0){const base=70+Math.floor(Math.random()*181),gain=Math.max(30,Math.round(base*CUSTOMER_TYPES[record.type].spend*machineMultiplier()));sales+=gain;cash+=gain;lifetimeSales+=gain;const stat=islandStats.get(record.target.facilityId);if(stat)stat.revenue+=gain}if(record.dwell<=0||gameMinute>=CLOSE_MINUTE)beginExit(record)}if(record.phase==='leave'){record.actor.remove();customers.delete(id)}}}
function clearCustomers(){for(const r of customers.values())r.actor.remove();customers.clear()}
function closeDay(){if(daySettled||customers.size)return;daySettled=true;const operating=18000+activeLayout.islands.length*4200,profit=Math.round(sales-operating);cash=Math.max(0,cash-operating);popularity=Math.max(1,Math.min(99,popularity+(profit>25000?1:profit<0?-1:0)));persist();setEvent(`営業終了　経費 ${fmt.format(operating)}G / 利益 ${fmt.format(profit)}G`);updateHud()}
function nextDay(){clearCustomers();day++;gameMinute=OPEN_MINUTE;sales=0;dayVisitors=0;speed=1;spawnClock=0;daySettled=false;adBoost=Math.max(0,adBoost-1);for(const s of islandStats.values()){s.plays=0;s.revenue=0}segmentStats.regular=segmentStats.quick=segmentStats.high=0;persist();setEvent('OPEN 10:00');updateHud()}
function showPanel(title,html){els.panelTitle.textContent=title;els.panelBody.innerHTML=html;els.panel.hidden=false}function closePanel(){els.panel.hidden=true}
function bindPanels(){document.getElementById('panelClose')?.addEventListener('click',closePanel);document.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',()=>{const action=btn.dataset.action;if(action==='build'||action==='replace'){openPlacementMode(action);return}if(action==='info')showPanel('ホール情報',`<p>総来店 ${fmt.format(lifetimeVisitors)}人</p><p>累計売上 ${fmt.format(lifetimeSales)}G</p><p>研究Lv ${researchLevel}</p>`);if(action==='manage')showPanel('経営',`<p>人気 ★${popularity}</p><p>サービスLv ${serviceBoost}</p><button id="serviceBtn">接客研修 30,000G</button>`);if(action==='ad')showPanel('広告',`<p>本日の集客力 +${adBoost}</p><button id="adBtn">地域広告 20,000G</button>`);if(action==='research')showPanel('研究',`<p>研究Lv ${researchLevel}</p><p>遊技単価 +${researchLevel*8}%</p><button id="researchBtn">台研究 50,000G</button>`);if(action==='customer')showPanel('客層',`<p>常連 ${segmentStats.regular}人</p><p>短時間客 ${segmentStats.quick}人</p><p>高単価客 ${segmentStats.high}人</p>`);if(action==='menu')showPanel('メニュー',`<p>1日を営業して店を育てます。</p><button id="saveBtn">セーブ</button>${daySettled?'<button id="nextDayBtn">翌日へ</button>':''}`);wirePanelButtons()}))}
function wirePanelButtons(){document.getElementById('saveBtn')?.addEventListener('click',()=>{persist();setEvent('セーブしました');closePanel()});document.getElementById('nextDayBtn')?.addEventListener('click',()=>{nextDay();closePanel()});document.getElementById('adBtn')?.addEventListener('click',()=>{if(cash<20000)return setEvent('資金不足');cash-=20000;adBoost+=8;setEvent('地域広告を開始');closePanel();updateHud()});document.getElementById('researchBtn')?.addEventListener('click',()=>{if(cash<50000)return setEvent('資金不足');cash-=50000;researchLevel++;setEvent(`台研究 Lv${researchLevel}`);persist();closePanel();updateHud()});document.getElementById('serviceBtn')?.addEventListener('click',()=>{if(cash<30000)return setEvent('資金不足');cash-=30000;serviceBoost++;setEvent(`接客研修 Lv${serviceBoost}`);closePanel();updateHud()})}
function openPlacementMode(mode){if(buildPanel?.isConnected)return;const target=activeLayout.islands[0];if(!target)return;speed=0;buildCursor=createPlacementCursor(activeLayout,{facilityId:target.id});buildPanel=document.createElement('div');buildPanel.className='placementPanel';buildPanel.innerHTML=`<b>${mode==='replace'?'台入替・配置':'建設・配置'}</b><span id="placeStatus">島を移動できます</span><button data-move="W">◀</button><button data-move="N">▲</button><button data-move="S">▼</button><button data-move="E">▶</button><button id="placeApply">決定</button><button id="placeCancel">戻る</button>`;document.querySelector('.game')?.appendChild(buildPanel);const status=buildPanel.querySelector('#placeStatus');bindPlacementCursorControls(buildPanel,buildCursor,{onMove:(next)=>{buildCursor=next;status.textContent=`候補 ${next.candidate.x},${next.candidate.y} ${next.valid?'OK':'NG'}`},onApply:(next)=>{buildCursor=next;if(!next.valid){status.textContent='この位置には置けません';return}activeLayout=next.layout;report=validateLayout(activeLayout);renderLayout(els.scene,activeLayout);buildPanel.remove();buildPanel=null;buildCursor=null;speed=1;setEvent('配置を変更しました');centerCamera()},onCancel:()=>{buildPanel.remove();buildPanel=null;buildCursor=null;speed=1;setEvent('配置をキャンセル')}})}
document.querySelectorAll('[data-speed]').forEach(btn=>btn.addEventListener('click',()=>{speed=Number(btn.dataset.speed);document.querySelectorAll('[data-speed]').forEach(b=>b.classList.toggle('active',b===btn));updateHud()}));
function tick(){if(speed>0&&!daySettled){for(let s=0;s<speed;s++){gameMinute=Math.min(CLOSE_MINUTE+90,gameMinute+2);if(gameMinute<CLOSE_MINUTE){spawnClock+=2;if(spawnClock>=spawnThreshold()){spawnClock=0;spawnCustomer()}}advanceCustomers();if(gameMinute>=CLOSE_MINUTE&&customers.size===0)closeDay()}}updateHud()}
renderLayout(els.scene,activeLayout);installCameraControls();bindPanels();centerCamera();updateHud();setInterval(tick,GAME_TICK_MS);
window.__CHAPPY_PLAYTEST_STATE__=()=>({day,gameMinute,cash,sales,dayVisitors,speed,customers:customers.size,popularity,researchLevel,settled:daySettled,layoutValid:report.ok,zoom});
