import { depthKey, projectedBounds, toScreen } from './grid.js';
import { BUILDING_SHELL, FLOOR_BOUNDS } from './layout.js';
import { directionFromDelta, pixelCharacterDataURL } from './pixel-characters.js';

const SVG_NS='http://www.w3.org/2000/svg';
function place(scene,element,item,extraRise=0){const point=toScreen(item.x,item.y,(item.rise??0)+extraRise);element.style.left=`${point.x}px`;element.style.top=`${point.y}px`;element.style.zIndex=String(100+Math.round(depthKey(item)));element.dataset.gridX=item.x;element.dataset.gridY=item.y;element.dataset.id=item.id;scene.appendChild(element);return element}
function line(svg,a,b,className){const n=document.createElementNS(SVG_NS,'line');n.setAttribute('x1',a.x);n.setAttribute('y1',a.y);n.setAttribute('x2',b.x);n.setAttribute('y2',b.y);n.setAttribute('class',className);svg.appendChild(n)}
function polygon(svg,points,className){const n=document.createElementNS(SVG_NS,'polygon');n.setAttribute('points',points.map(p=>`${p.x},${p.y}`).join(' '));n.setAttribute('class',className);svg.appendChild(n)}
function renderLogicalGrid(scene){scene.querySelector('.logicalGrid')?.remove();const svg=document.createElementNS(SVG_NS,'svg');svg.setAttribute('class','logicalGrid');svg.setAttribute('width',scene.clientWidth||730);svg.setAttribute('height',scene.clientHeight||530);for(let x=FLOOR_BOUNDS.minX;x<=FLOOR_BOUNDS.maxX+1;x++)line(svg,toScreen(x,FLOOR_BOUNDS.minY),toScreen(x,FLOOR_BOUNDS.maxY+1),'gridLine');for(let y=FLOOR_BOUNDS.minY;y<=FLOOR_BOUNDS.maxY+1;y++)line(svg,toScreen(FLOOR_BOUNDS.minX,y),toScreen(FLOOR_BOUNDS.maxX+1,y),'gridLine');scene.appendChild(svg)}
function wallEdge(w){if(w.y===FLOOR_BOUNDS.minY)return{a:{x:w.x,y:w.y},b:{x:w.x+1,y:w.y},back:true};if(w.x===FLOOR_BOUNDS.minX)return{a:{x:w.x,y:w.y},b:{x:w.x,y:w.y+1},back:true};if(w.y===FLOOR_BOUNDS.maxY)return{a:{x:w.x,y:w.y+1},b:{x:w.x+1,y:w.y+1},back:false};if(w.x===FLOOR_BOUNDS.maxX)return{a:{x:w.x+1,y:w.y},b:{x:w.x+1,y:w.y+1},back:false};return null}
function renderWalls(scene){scene.querySelector('.wallFaces')?.remove();const svg=document.createElementNS(SVG_NS,'svg');svg.setAttribute('class','wallFaces');svg.setAttribute('width',scene.clientWidth||730);svg.setAttribute('height',scene.clientHeight||530);for(const w of BUILDING_SHELL.walls){const e=wallEdge(w);if(!e)continue;const rise=e.back?34:8,a=toScreen(e.a.x,e.a.y),b=toScreen(e.b.x,e.b.y),ar=toScreen(e.a.x,e.a.y,rise),br=toScreen(e.b.x,e.b.y,rise);polygon(svg,[a,b,br,ar],e.back?'wallFace wallFaceBack':'wallFace wallFaceFront');line(svg,ar,br,e.back?'wallCap wallCapBack':'wallCap wallCapFront')}scene.appendChild(svg)}
function renderMapBase(scene){const bounds=projectedBounds(FLOOR_BOUNDS),floor=scene.querySelector('.floor'),lot=scene.querySelector('.lot'),road=scene.querySelector('.road');floor.style.left=`${bounds.left}px`;floor.style.top=`${bounds.top}px`;floor.style.width=`${bounds.width}px`;floor.style.height=`${bounds.height}px`;lot.style.display='none';road.style.display='none';const sceneWidth=Math.ceil(Math.max(730,bounds.right+14)),sceneHeight=Math.ceil(bounds.bottom+80);scene.style.width=`${sceneWidth}px`;scene.style.height=`${sceneHeight}px`;scene.dataset.baseWidth=sceneWidth;scene.dataset.baseHeight=sceneHeight;scene.querySelector('.interiorZones')?.remove();renderLogicalGrid(scene);renderWalls(scene)}
function variantFor(id=''){let h=0;for(let i=0;i<id.length;i++)h=(h*31+id.charCodeAt(i))>>>0;return h%12}
function applyCustomerSprite(actor,customer,type){const oldX=Number(actor.dataset.gridX??customer.x),oldY=Number(actor.dataset.gridY??customer.y);const dir=directionFromDelta(customer.x-oldX,customer.y-oldY,actor.dataset.dir||'SE');actor.dataset.dir=dir;const frame=(Number(actor.dataset.walkFrame||0)+1)%4;actor.dataset.walkFrame=frame;const variant=Number(actor.dataset.customerVariant||0);actor.src=pixelCharacterDataURL(type||actor.dataset.customerType||'regular',dir,frame,false,variant)}
export function renderCustomerActor(scene,customer,type='regular'){const actor=document.createElement('img');actor.className='gridNode customerActor pixelCustomer';actor.alt='';actor.draggable=false;const variant=variantFor(customer.id);actor.dataset.customerType=type;actor.dataset.customerVariant=String(variant);actor.dataset.dir='SE';actor.dataset.walkFrame='0';actor.src=pixelCharacterDataURL(type,'SE',0,false,variant);return place(scene,actor,{id:customer.id,x:customer.x,y:customer.y,w:1,d:1,rise:22})}
export function updateCustomerActor(actor,customer){applyCustomerSprite(actor,customer,actor.dataset.customerType||'regular');const point=toScreen(customer.x,customer.y,22);actor.style.left=`${point.x}px`;actor.style.top=`${point.y}px`;actor.style.zIndex=String(100+Math.round(customer.x+customer.y));actor.dataset.gridX=customer.x;actor.dataset.gridY=customer.y;actor.dataset.customerState=customer.state}
export function renderLayout(scene){scene.querySelectorAll('.gridNode').forEach(n=>n.remove());renderMapBase(scene)}
