// ZELVOLT native 3-reel engine v1.16
// 3-row physical reels + 5-line A-type pull-in / miss / stop-order control.
(()=>{
  const STRIPS=[
    ['7R','BELL','GRAPE','CHERRY','BELL','BAR','GRAPE','BELL','REPLAY','GRAPE','CHERRY','BELL','7W','GRAPE','BELL','CHERRY','BAR','GRAPE','BELL','REPLAY','GRAPE'],
    ['GRAPE','BELL','BAR','CHERRY','GRAPE','BELL','REPLAY','GRAPE','BELL','7R','CHERRY','GRAPE','BELL','BAR','GRAPE','7W','BELL','CHERRY','GRAPE','BELL','REPLAY'],
    ['BELL','GRAPE','CHERRY','BAR','BELL','GRAPE','REPLAY','CHERRY','BELL','GRAPE','7R','BELL','GRAPE','BAR','CHERRY','BELL','7W','GRAPE','REPLAY','BELL','GRAPE']
  ];
  const WINDOW=102,ROWS=3,ROW=WINDOW/ROWS;
  const SPEED=[0.68,0.68,0.68],ACCEL=0.0052,START_VELOCITY=0.095;
  const STOP_REACTION_MS=46,MIN_STOP_TRAVEL=ROW*0.72,MIN_STOP_MS=150,MAX_STOP_MS=245;
  const MAX_SLIP_SYMBOLS=4;
  const LINES=[
    {name:'TOP',rows:[0,0,0]},
    {name:'MIDDLE',rows:[1,1,1]},
    {name:'BOTTOM',rows:[2,2,2]},
    {name:'DOWN',rows:[0,1,2]},
    {name:'UP',rows:[2,1,0]}
  ];
  const TRIPLE_WIN_CODES=new Set(['7R','7W','BAR','BELL','GRAPE','REPLAY']);
  const reelsView=[];const stopControlState=[null,null,null];const stopSequence=[];let activeLine=null;
  const mod=(n,m)=>((n%m)+m)%m,now=()=>performance.now(),normalizeCode=code=>code==='STAR'?'REPLAY':code;
  function clearLegacyTimer(i){if(timers[i]!=null){clearInterval(timers[i]);timers[i]=null}}
  function clearLegacyTimers(){for(let i=0;i<3;i++)clearLegacyTimer(i)}
  function addStyle(){if(document.getElementById('zelvolt-native-reels-style'))return;const s=document.createElement('style');s.id='zelvolt-native-reels-style';s.textContent=`.reel{height:${WINDOW}px!important;overflow:hidden!important;display:block!important;position:relative!important;background:linear-gradient(90deg,#d9d9d9,#fff 16%,#fff 84%,#d9d9d9)!important;transition:box-shadow .11s ease,background .11s ease}.reel>.symbol{display:none!important}.zv-native-track{position:absolute;left:0;right:0;top:0;will-change:transform;backface-visibility:hidden;transform:translate3d(0,0,0)}.zv-native-cell{height:${ROW}px;display:flex;align-items:center;justify-content:center}.zv-native-cell img{display:block;width:38px;height:38px;object-fit:contain;pointer-events:none;user-select:none;-webkit-user-drag:none}.zv-native-payline{position:absolute;z-index:4;left:2px;right:2px;top:${ROW}px;height:${ROW}px;border-top:1px solid rgba(255,215,55,.35);border-bottom:1px solid rgba(255,215,55,.35);pointer-events:none}.zv-native-shadow{position:absolute;z-index:5;inset:0;pointer-events:none;background:linear-gradient(180deg,rgba(0,0,0,.16),transparent 18%,transparent 82%,rgba(0,0,0,.16))}.reel.zv-native-lit{background:linear-gradient(90deg,#dededb,#fffef5 16%,#fffef8 84%,#dededb)!important;box-shadow:inset 0 0 9px rgba(255,244,190,.20),0 0 4px rgba(255,239,160,.10)!important}.reel.zv-native-spinning .zv-native-track{filter:blur(.16px)}.reel.zv-native-stopping .zv-native-track{filter:blur(.025px)}.reel.zv-native-settle{animation:zvReelSettle .085s ease-out}@keyframes zvReelSettle{0%{transform:translateY(1px)}100%{transform:translateY(0)}}`;document.head.appendChild(s)}
  function makeCell(code){const c=document.createElement('div');c.className='zv-native-cell';const img=document.createElement('img');img.alt=code;img.draggable=false;img.src=symbolFiles[normalizeCode(code)];c.appendChild(img);return c}
  function buildReel(i){const host=document.getElementById('r'+(i+1));if(!host)return null;host.textContent='';const track=document.createElement('div');track.className='zv-native-track';for(let copy=0;copy<3;copy++)for(const code of STRIPS[i])track.appendChild(makeCell(code));const payline=document.createElement('div');payline.className='zv-native-payline';const shadow=document.createElement('div');shadow.className='zv-native-shadow';host.append(track,payline,shadow);const v={host,track,strip:STRIPS[i],cycle:STRIPS[i].length*ROW,phase:0,velocity:0,spinning:false,stopping:false,stopIndex:null,raf:0,last:0};reelsView[i]=v;return v}
  function render(v){const p=mod(v.phase,v.cycle);v.track.style.transform=`translate3d(0,${-v.cycle+p}px,0)`}
  function setReelLight(v,on){if(!v)return;v.host.classList.toggle('zv-native-lit',!!on)}
  function setAllReelLights(on){for(const v of reelsView)setReelLight(v,on)}
  function phaseForIndex(index,cycle){return mod(ROW-index*ROW,cycle)}
  function symbolAtRow(v,middleIndex,row){return v.strip[mod(middleIndex+(row-1),v.strip.length)]}
  function rowsAtIndex(v,middleIndex){return[0,1,2].map(row=>symbolAtRow(v,middleIndex,row))}
  function middleIndexForSymbolRow(v,symbolIndex,row){return mod(symbolIndex-(row-1),v.strip.length)}
  function indexForSymbolAtRow(v,code,row,minTravel=0){code=normalizeCode(code);const current=v.phase;let best=null;for(let symbolIndex=0;symbolIndex<v.strip.length;symbolIndex++){if(v.strip[symbolIndex]!==code)continue;const middleIndex=middleIndexForSymbolRow(v,symbolIndex,row);const targetBase=phaseForIndex(middleIndex,v.cycle);let delta=mod(targetBase-mod(current,v.cycle),v.cycle);while(delta<minTravel)delta+=v.cycle;if(!best||delta<best.delta)best={index:middleIndex,delta,target:current+delta,row,symbolIndex}}return best}
  function nearestIndexForCode(v,code,minTravel=0){return indexForSymbolAtRow(v,code,1,minTravel)}
  function naturalStopFromPhase(v,phase){let best=null;for(let index=0;index<v.strip.length;index++){const targetBase=phaseForIndex(index,v.cycle);let delta=mod(targetBase-mod(phase,v.cycle),v.cycle);while(delta<MIN_STOP_TRAVEL)delta+=v.cycle;if(!best||delta<best.delta)best={index,delta,target:phase+delta}}return best}
  function controlCodeForReel(i){if(['BIG','REG','REPLAY','BELL','GRAPE'].includes(resultType))return normalizeCode(targetSymbol);if(resultType==='CHERRY'&&i===0)return'CHERRY';return null}
  function intendedTripleCode(){if(resultType==='BIG')return normalizeCode(targetSymbol);if(resultType==='REG')return'BAR';if(['REPLAY','BELL','GRAPE'].includes(resultType))return normalizeCode(targetSymbol);return null}
  function resolvedMiddleIndex(i){const decision=stopControlState[i];if(decision&&Number.isInteger(decision.finalIndex))return decision.finalIndex;const v=reelsView[i];return Number.isInteger(v?.stopIndex)?v.stopIndex:null}
  function candidateGrid(reelIndex,candidateIndex){return[0,1,2].map(i=>{const v=reelsView[i];if(!v)return[null,null,null];const index=i===reelIndex?candidateIndex:resolvedMiddleIndex(i);return index==null?[null,null,null]:rowsAtIndex(v,index)})}
  function unintendedWinsForGrid(grid){const unintended=[];const intended=intendedTripleCode();for(const line of LINES){const symbols=line.rows.map((row,i)=>grid[i][row]);if(symbols.every(Boolean)&&symbols[0]===symbols[1]&&symbols[1]===symbols[2]&&TRIPLE_WIN_CODES.has(symbols[0])){if(symbols[0]!==intended)unintended.push({type:'TRIPLE',code:symbols[0],line:line.name})}if(resultType!=='CHERRY'&&symbols[0]==='CHERRY')unintended.push({type:'CHERRY',code:'CHERRY',line:line.name})}return unintended}
  function safeNaturalCandidate(i,v,projected,natural){let fallback={index:natural.index,target:natural.target,slip:0,unintended:unintendedWinsForGrid(candidateGrid(i,natural.index))};if(!fallback.unintended.length)return fallback;for(let slip=1;slip<=MAX_SLIP_SYMBOLS;slip++){const index=mod(natural.index-slip,v.strip.length);const target=natural.target+slip*ROW;const unintended=unintendedWinsForGrid(candidateGrid(i,index));if(!unintended.length)return{index,target,slip,unintended:[]}}return fallback}
  function inspectStopControl(i){const v=reelsView[i];if(!v)return null;if(!stopSequence.includes(i))stopSequence.push(i);const normalized=controlCodeForReel(i);const reactionVelocity=Math.max(v.velocity,SPEED[i]*.86);const projected=v.phase+reactionVelocity*STOP_REACTION_MS;const natural=naturalStopFromPhase(v,projected);const targetRow=normalized&&activeLine?activeLine.rows[i]:1;let best=null;if(normalized){for(let symbolIndex=0;symbolIndex<v.strip.length;symbolIndex++){if(v.strip[symbolIndex]!==normalized)continue;const middleIndex=middleIndexForSymbolRow(v,symbolIndex,targetRow);const targetBase=phaseForIndex(middleIndex,v.cycle);let delta=mod(targetBase-mod(projected,v.cycle),v.cycle);while(delta<natural.delta)delta+=v.cycle;const slip=Math.max(0,Math.round((delta-natural.delta)/ROW));if(!best||slip<best.slip||slip===best.slip&&delta<best.delta)best={middleIndex,symbolIndex,delta,slip,target:projected+delta}}}
    const canPull=!!best&&best.slip<=MAX_SLIP_SYMBOLS;
    const safeNatural=safeNaturalCandidate(i,v,projected,natural);
    const finalIndex=canPull?best.middleIndex:safeNatural.index;
    const finalTarget=canPull?best.target:safeNatural.target;
    const logicalRow=activeLine?activeLine.rows[i]:1;
    const finalSymbol=symbolAtRow(v,finalIndex,logicalRow);
    const unintended=unintendedWinsForGrid(candidateGrid(i,finalIndex));
    const state={reel:i,stopOrder:stopSequence.length,pressPhase:v.phase,projectedPhase:projected,naturalIndex:natural.index,naturalSymbol:symbolAtRow(v,natural.index,logicalRow),targetCode:normalized||null,targetRow:normalized?targetRow:null,requiredSlip:best?best.slip:null,canPull,missed:!!normalized&&!canPull,appliedSlip:canPull?best.slip:safeNatural.slip,maxSlipSymbols:MAX_SLIP_SYMBOLS,finalIndex,finalTarget,finalSymbol,logicalRow,antiAccidentalAdjusted:!canPull&&safeNatural.slip>0,unintendedWins:unintended};
    stopControlState[i]=state;
    reels[i]=finalSymbol;
    return state
  }
  function chooseLine(){return LINES[Math.floor(Math.random()*LINES.length)]}
  function guaranteedCode(){if(['BIG','REG','REPLAY','BELL','GRAPE'].includes(resultType))return normalizeCode(targetSymbol);if(resultType==='CHERRY')return'CHERRY';return null}
  function resolvedRows(i){const v=reelsView[i],middleIndex=resolvedMiddleIndex(i);if(!v||middleIndex==null)return[null,null,null];return rowsAtIndex(v,middleIndex)}
  function fiveLineOutcome(){const rows=[0,1,2].map(i=>resolvedRows(i));const complete=rows.every(r=>r.every(Boolean));const lines=LINES.map(line=>({name:line.name,rows:[...line.rows],symbols:line.rows.map((row,i)=>rows[i][row])}));return{complete,rows,lines,stopOrder:[...stopSequence],unintendedWins:complete?unintendedWinsForGrid(rows):[]}}
  function setStatic(i,code){const v=reelsView[i]||buildReel(i);if(!v)return;if(v.raf)cancelAnimationFrame(v.raf);v.raf=0;v.spinning=false;v.stopping=false;v.velocity=0;setReelLight(v,true);v.host.classList.remove('zv-native-spinning','zv-native-stopping','zv-native-settle');const hit=nearestIndexForCode(v,normalizeCode(code),0);if(hit){v.phase=hit.target;v.stopIndex=hit.index}render(v)}
  function startPhysical(i){const v=reelsView[i]||buildReel(i);if(!v||v.spinning||v.stopping)return;v.spinning=true;v.stopIndex=null;stopControlState[i]=null;v.velocity=Math.max(v.velocity,START_VELOCITY);v.last=now();setReelLight(v,true);v.host.classList.remove('zv-native-stopping','zv-native-settle');v.host.classList.add('zv-native-spinning');const step=t=>{if(!v.spinning)return;const dt=Math.min(34,t-v.last||16.7);v.last=t;v.velocity=Math.min(SPEED[i],v.velocity+dt*ACCEL);v.phase+=v.velocity*dt;render(v);v.raf=requestAnimationFrame(step)};v.raf=requestAnimationFrame(step)}
  function stopPhysical(i,code){const v=reelsView[i]||buildReel(i);if(!v)return;code=normalizeCode(code);const decision=inspectStopControl(i);if(!v.spinning&&!v.stopping){setStatic(i,reels[i]||code);return}if(v.raf)cancelAnimationFrame(v.raf);v.raf=0;v.spinning=false;v.stopping=true;v.host.classList.remove('zv-native-spinning','zv-native-settle');v.host.classList.add('zv-native-stopping');const reactionVelocity=Math.max(v.velocity,SPEED[i]*.86),reactionT0=now();const coast=t=>{const elapsed=t-reactionT0,dt=Math.min(34,t-(v.last||reactionT0)||16.7);v.last=t;v.phase+=reactionVelocity*dt;render(v);if(elapsed<STOP_REACTION_MS){v.raf=requestAnimationFrame(coast);return}beginSettle()};const beginSettle=()=>{let target=decision?.finalTarget??null;if(target==null){const natural=naturalStopFromPhase(v,v.phase);target=natural.target;if(decision){decision.finalIndex=natural.index;decision.finalTarget=target;decision.finalSymbol=symbolAtRow(v,natural.index,decision.logicalRow??1);reels[i]=decision.finalSymbol}}while(target-v.phase<MIN_STOP_TRAVEL)target+=v.cycle;const finalIndex=decision?.finalIndex??naturalStopFromPhase(v,v.phase).index;const start=v.phase,distance=target-start,duration=Math.max(MIN_STOP_MS,Math.min(MAX_STOP_MS,125+distance/.62)),t0=now(),ease=t=>1-Math.pow(1-t,4.7);const settle=t=>{const q=Math.min(1,(t-t0)/duration);v.phase=start+distance*ease(q);render(v);if(q<1){v.raf=requestAnimationFrame(settle);return}v.phase=target;v.stopIndex=finalIndex;v.velocity=0;v.stopping=false;v.raf=0;v.host.classList.remove('zv-native-stopping');v.host.classList.add('zv-native-settle');render(v);setTimeout(()=>v.host.classList.remove('zv-native-settle'),100)};v.raf=requestAnimationFrame(settle)};v.last=reactionT0;v.raf=requestAnimationFrame(coast)}
  function visibleRows(i){return resolvedRows(i)}
  function init(){addStyle();for(let i=0;i<3;i++){buildReel(i);setStatic(i,reels[i])}setAllReelLights(true);window.drawReel=function(i){if(i<0||i>2)return;if(spinning[i])return;stopPhysical(i,reels[i])};window.drawAllReels=function(){for(let i=0;i<3;i++)setStatic(i,reels[i])};const machineStart=window.start;window.start=function(){const before=[...spinning];machineStart();clearLegacyTimers();activeLine=guaranteedCode()?chooseLine():null;stopSequence.length=0;for(let i=0;i<stopControlState.length;i++)stopControlState[i]=null;for(let i=0;i<3;i++)if(spinning[i]&&!before[i])startPhysical(i)};const machineStop=window.stop;window.stop=function(i){if(i<0||i>2||!spinning[i])return;clearLegacyTimer(i);machineStop(i)};const machineReset=window.resetGame;window.resetGame=function(){clearLegacyTimers();activeLine=null;stopSequence.length=0;for(let i=0;i<stopControlState.length;i++)stopControlState[i]=null;for(const v of reelsView){if(v?.raf)cancelAnimationFrame(v.raf)}machineReset();clearLegacyTimers();for(let i=0;i<3;i++)setStatic(i,reels[i]);setAllReelLights(true)};window.ZELVOLT_REELS={strips:STRIPS.map(s=>[...s]),lines:LINES.map(x=>({name:x.name,rows:[...x.rows]})),tuning:{speed:[...SPEED],accel:ACCEL,reactionMs:STOP_REACTION_MS,minStopTravel:MIN_STOP_TRAVEL,minStopMs:MIN_STOP_MS,maxStopMs:MAX_STOP_MS,direction:'down'},stopControl:{maxSlipSymbols:MAX_SLIP_SYMBOLS,mode:'4-symbol-pull-in+anti-accidental',getLast:()=>stopControlState.map(x=>x?{...x}:null),getOrder:()=>[...stopSequence]},lighting:{mode:'normally-on',strength:'subtle',set:(i,on)=>setReelLight(reelsView[i],on),setAll:setAllReelLights},getState:()=>reelsView.map((v,i)=>({reel:i,phase:v?.phase??0,velocity:v?.velocity??0,spinning:!!v?.spinning,stopping:!!v?.stopping,lit:!!v?.host.classList.contains('zv-native-lit'),stopIndex:resolvedMiddleIndex(i),rows:visibleRows(i),stopControl:stopControlState[i]?{...stopControlState[i]}:null})),getOutcome:fiveLineOutcome,getActiveLine:()=>activeLine?{name:activeLine.name,rows:[...activeLine.rows]}:null}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
